# Generated by Django 5.0.4 on 2024-07-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_alter_store_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(),
        ),
    ]
