# Generated by Django 5.0.4 on 2024-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_name_alter_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('待上架', '待上架'), ('上架中', '上架中'), ('刪除', '刪除')], default='待上架', max_length=50),
        ),
    ]
