# Generated by Django 5.0.4 on 2024-07-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
