# Generated by Django 5.0.4 on 2024-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_phone_alter_store_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='index',
        ),
        migrations.AddField(
            model_name='table',
            name='slug',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
