# Generated by Django 5.0.4 on 2024-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(default=123254613148, max_length=255),
            preserve_default=False,
        ),
    ]
